= Школьный проект

== план

=== 1) Проблематика

Киберугрозы:

* перехват данных третьими лицами,
* подмена данных
* отсутствие анонимности
* централизация управления

=== 2) Теоретическая часть

Основы криптографии:

* Понятия: шифрование, дешифрование, ключи
* Типы шифров: симметричные (AES) и асимметричные (RSA)
* Хэш Функции
* Подпись
* Цепочки подписей (блокчейн)

=== 3) Блокчейн

Как средство децентрализованного хранения информации

Использование нескольких реестров для достижения анонмности и базопасности

=== 4) Предполагаемый процесс использования

=== Топология, каждый узел знает только своих соседей

[plantuml,nodes, png]
----
@startuml
'https://plantuml.com/component-diagram

[Алиса node] <---> [node1]
[node1] <--> [node2]
[node2] <-> [node3]
[node3] <---> [Bob node]
[Bob node] <-> [node5]
[node5] <---> [node6]
[node6] <-> [Алиса node]

@enduml
----

=== Процес передачи сообщения

[plantuml, nodes, png]
----

@startuml

Alice -> B3: Ищет публичный ключ Боба,\n по username
Alice <-- B3: публичный ключ Боба  

Alice -> B1: Ищет входящий узел до Боба
Alice <-- B1: Возвращается цепочка узлов от входящего узла до Боба
  
Alice -> Alice: Высчитывает цепочку узлов до входящего узла Боба

Alice -> Alice: Шифрует сообщение ключом Боба
Alice -> Alice: Отправляет сообщение с маршрутом      
  
@enduml
----

=== Хранение

|===
|блокчейн | 

|B1 |Реестр маршрутов, с входящими узлами 
|B2 |Реестр узлов, для построения маршрутов 
|B3 |Реестр Username - публичный ключ для сообщений 
|===

== Результат

Полная анонимность, невозможно получить все физические адреса пользователей, невозможно получить физический адрес получателя и отправителя, построить графф получателя и отправителя.
Не возможно прочесть сообщения.
Возможно всегда проверить, достоверность отправителя